name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install -U pip poetry
          poetry install
      - name: Run black
        run: black . --check
      - name: Run flake8
        run: flake8 --count --show-source --statistics
      - name: Run isort
        run: isort . -c
      - name: Run tests
        run: python -m pytest
